# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e84f904d298ed648350ebe548ce67588461c7d731f15c35c02a6b600a1ae313230ac83a44c7079ba07a867c0c2cacfb15a653d3467cbecec1c049fb8019c218d

test:
  secret_key_base: c012e1cfc2b38684b375c5dc11b516f7b61bb0bc600b97e7848c751db53f2f99eec5e10bfc8066c9b28fd1a4176bab175a441ffc8c32dbc6186d1af38cb27dbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
